import { Geist, Geist_Mono } from 'next/font/google'
import { type ReactNode, Suspense } from 'react'

import type { Metadata } from 'next'

import { MSWProvider } from '@/components/MSWProvider'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode
}>) => (
  <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Suspense>
        <MSWProvider>{children}</MSWProvider>
      </Suspense>
    </body>
  </html>
)

export default RootLayout
